# Generated by Django 4.2.4 on 2023-09-08 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_userprofile_oauth_token_secret_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="oauth_token_secret",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="twitter_id",
        ),
    ]
