# Generated by Django 4.2.4 on 2023-09-08 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_userprofile_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="website",
        ),
    ]
