# Generated by Django 4.2.4 on 2023-10-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_project_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="tweets_left",
            field=models.IntegerField(default=2000),
        ),
    ]
