# Generated by Django 4.2.4 on 2023-10-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_userprofile_tweets_left"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_whitelisted",
            field=models.BooleanField(default=False),
        ),
    ]
