# Generated by Django 4.2.4 on 2023-10-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_userprofile_is_whitelisted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="tweets_left",
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
