# Generated by Django 4.2.4 on 2023-12-04 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_project_keywords"),
        ("core", "0019_project_token"),
    ]

    operations = []
