# Generated by Django 4.2.4 on 2023-09-01 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_TweetsModel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tweets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("tweet_content", models.TextField()),
                ("ai_response", models.TextField(default=None, null=True)),
                ("misc_data", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("FETCHED", "FETCHED"),
                            ("APPROVED", "APPROVED"),
                            ("POSTED", "POSTED"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.project"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
