# Generated by Django 4.2.4 on 2023-10-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0004_tweets_author_id_tweets_tweet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweets",
            name="state",
            field=models.CharField(
                choices=[("FETCHED", "FETCHED"), ("POSTED", "POSTED")], max_length=255
            ),
        ),
    ]
