# Generated by Django 4.2.4 on 2023-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0005_alter_tweets_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweets",
            name="bookmark_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tweets",
            name="impression_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tweets",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tweets",
            name="quote_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tweets",
            name="reply_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tweets",
            name="retweet_count",
            field=models.IntegerField(default=0),
        ),
    ]
