# Generated by Django 4.2.4 on 2023-12-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("listner", "0004_quest_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tguser",
            name="quest",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="listner.quest",
            ),
            preserve_default=False,
        ),
    ]
